name: "Podcast Generator"
author: Samuel G. Moreno
description: "Generates a feed for a Podcast from a YAML file."
runs:
  using: "docker"
  image: 'Dockerfile'
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
  description: The committer's email address
  required: true
  default: ${{ github.actor }}@localhost
name: 
  description: The committer's name.
  required: true
  default: ${{ github.actor }}